import Telescope from 'meteor/nova:lib';
import zh from 'react-intl/locale-data/zh';
import { addLocaleData } from 'react-intl';

addLocaleData([...zh]);

Telescope.strings['zh-CN'] = {
  "forms.submit": "提交",
  "forms.cancel": "取消",

  "posts.new_post": "新帖",
  "posts.edit": "编辑",
  "posts.edit_success": "“{title}”编辑成功",
  "posts.delete": "删除",
  "posts.delete_confirm": "确认删除“{title}”?",
  "posts.delete_success": "“{title}”删除成功",
  "posts.title": "标题",
  "posts.url": "链接",
  "posts.body": "内容",
  "posts.categories": "文章分类",
  "posts.thumbnailUrl": "缩略图",
  "posts.status": "状态",
  "posts.sticky": "置顶",
  "posts.load_more": "拉取更多",
  "posts.load_more_days": "拉取更多天数",
  "posts.no_more": "已显示所有文章",
  "posts.no_results": "暂无文章",
  "posts.search": "搜索",
  "posts.view": "查看方式",
  "posts.top": "最🔥",
  "posts.new": "最新",
  "posts.best": "最好",
  "posts.pending": "待审核",
  "posts.rejected": "已驳回",
  "posts.scheduled": "已排挡",
  "posts.daily": "按日期",
  "posts.clear_thumbnail": "清除缩略图",
  "posts.enter_thumbnail_url": "输入URL",
  "posts.created_message": "提交成功",
  "posts.rate_limit_error": "{details}秒后才能再次发帖",
  "posts.postedAt": "发表时间",
  "posts.dateNotDefined": "无日期信息",
  "posts.subscribe": "订阅",
  "posts.unsubscribe": "退订",
  "posts.subscribed": "已订阅“{name}”的评论",
  "posts.unsubscribed": "已退订“{name}”的评论",
  "posts.subscribed_posts": "订阅内容",
  "posts.link_already_posted": "这个链接已经被发布过",

  "comments.comments": "评论",
  "comments.count": "{count, plural, =0 {0 评论} one {# 评论} other {# 评论}}",
  "comments.new": "新建评论",
  "comments.no_comments": "暂无评论",
  "comments.reply": "回复",
  "comments.edit": "编辑",
  "comments.delete": "删除",
  "comments.delete_confirm": "删除“{body}”?",
  "comments.delete_success": "“{body}”已删除",
  "comments.please_log_in": "请登录后发表评论",
  "comments.parentCommentId": "上一层评论ID",
  "comments.topLevelCommentId": "最顶层评论ID",
  "comments.body": "内容",
  "comments.rate_limit_error": "{details}秒后才能再次评论",

  "users.profile": "个人信息",
  "users.complete_profile": "完善个人信息",
  "users.edit_account": "编辑账户",
  "users.edit_success": "用户“{name}”更新成功",
  "users.log_in": "登录",
  "users.log_out": "退出登录",
  "users.telescope.bio": "简介",
  "users.telescope.displayName": "显示名称",
  "users.telescope.email": "邮箱",
  "users.telescope.twitterUsername": "Twitter用户名",
  "users.telescope.website": "网站",
  "users.telescope.groups": "群组",
  "users.telescope.avatar": "头像",
  "users.notifications": "通知",
  "users.telescope.notifications_users": "新用户通知",
  "users.telescope.notifications_posts": "新文章通知",
  "users.telescope.newsletter_subscribeToNewsletter": "订阅电子报",
  "users.admin": "管理员",
  "users.isAdmin": "管理员",
  "users.posts": "文章",
  "users.please_log_in": "请登录",
  "users.cannot_post": "抱歉，您暂无发表权限",
  "users.subscribe": "订阅该用户内容",
  "users.unsubscribe": "退订该用户内容",
  "users.subscribed": "已订阅“{name}”的内容",
  "users.unsubscribed": "已退订“{name}”的内容",
  "users.subscribers": "订阅用户",

  "categories": "内容分类",
  "categories.all": "所有分类",
  "categories.edit": "编辑分类",
  "categories.new": "新建分类",
  "categories.delete": "删除分类",
  "categories.name": "名称",
  "categories.description": "描述",
  "categories.order": "次序",
  "categories.slug": "Slug",
  "categories.image": "图片",
  "categories.parentId": "上一级分类ID",
  "categories.subscribe": "订阅本栏文章",
  "categories.unsubscribe": "退订本栏文章",
  "categories.subscribed": "已订阅“{name}”的文章.",
  "categories.unsubscribed": "已退订“{name}”的文章",
  "categories.subscribed_categories": "已订阅分类",

  "settings": "设置",
  "settings.json_message": "请注意：与<code>settings.json</code>重复的设置将会无效",
  "settings.edit": "编辑设置",
  "settings.edited": "设置已更新（请刷新页面）",
  "settings.title": "标题",
  "settings.siteUrl": "网站链接",
  "settings.tagline": "标语",
  "settings.description": "描述",
  "settings.siteImage": "网站图片",
  "settings.defaultEmail": "默认邮箱",
  "settings.mailUrl": "邮箱服务器URL",
  "settings.scoreUpdate": "分数更新",
  "settings.postInterval": "发帖时间间隔",
  "settings.RSSLinksPointTo": "RSS链接指向",
  "settings.commentInterval": "评论时间间隔",
  "settings.maxPostsPerDay": "每日最高发帖数",
  "settings.startInvitesCount": "开始邀请计数",
  "settings.postsPerPage": "每页文章数",
  "settings.logoUrl": "Logo链接",
  "settings.logoHeight": "Logo高度",
  "settings.logoWidth": "Logo宽度",
  "settings.faviconUrl": "favicon链接",
  "settings.twitterAccount": "Twitter账户",
  "settings.facebookPage": "Facebook页面",
  "settings.googleAnalyticsId": "Google Analytics ID",
  "settings.locale": "Locale",
  "settings.requireViewInvite": "需要邀请才能查看",
  "settings.requirePostInvite": "需要邀请才能发表",
  "settings.requirePostsApproval": "文章需要审核",
  "settings.scoreUpdateInterval": "分数更新间隔",

  "app.loading": "正在加载…",
  "app.404": "抱歉，没有找到相关页面.",
  "app.powered_by": "Telescope驱动",
  "app.or": "或",
  "app.noPermission": "抱歉，您无权限执行本操作",

  "newsletter": "电子报",
  "newsletter.subscribe": "订阅",
  "newsletter.unsubscribe": "退订",
  "newsletter.subscribe_prompt": "订阅电子报",
  "newsletter.email": "邮箱",
  "newsletter.success_message": "感谢订阅🙏",

  "admin": "管理员",
  "notifications": "通知",
};
