import Telescope from 'meteor/nova:lib';

Telescope.strings.en = {
  "forms.submit": "提交",
  "forms.cancel": "取消",

  "posts.new_post": "新的帖子",
  "posts.edit": "编辑",
  "posts.edit_success": "帖子 “{title}” 编辑成功.",
  "posts.delete": "删除",
  "posts.delete_confirm": "确定删除 “{title}”?",
  "posts.delete_success": "“{title}” 已经删除.",
  "posts.title": "标题",
  "posts.url": "网址链接",
  "posts.body": "内容",
  "posts.categories": "类别",
  "posts.thumbnailUrl": "缩略图",
  "posts.status": "状态",
  "posts.sticky": "置顶",
  "posts.load_more": "加载更多",
  "posts.search": "搜索",
  "posts.view": "浏览",
  "posts.top": "最热",
  "posts.new": "最新",
  "posts.best": "点赞最多",
  "posts.pending": "正在审核的",
  "posts.rejected": "未通过的",
  "posts.scheduled": "Scheduled",
  "posts.daily": "当日",
  "posts.clear_thumbnail": "清除缩略图",
  "posts.enter_thumbnail_url": "输入缩略图网址链接",
  "posts.created_message": "帖子已发布.",
  "posts.rate_limit_error": "请 {details} 秒后再次尝试发布",
  "posts.postedAt": "Posted at",
  "posts.dateNotDefined": "未指定日期",
  "posts.subscribe": "订阅",
  "posts.unsubscribe": "取消订阅",
  "posts.subscribed": "您已订阅用户 “{name}” 的评论.",
  "posts.unsubscribed": "您已取消订阅用户 “{name}” 的评论.",
  "posts.subscribed_posts" : "Posts subscribed to",
  "posts.link_already_posted": "这条链接已经被发布了",

  "comments.comments": "评论",
  "comments.count": "{count, plural, =0 {No comments} one {# comment} other {# comments}}",
  "comments.new": "新评论",
  "comments.no_comments": "没有新评论",
  "comments.reply": "回复",
  "comments.edit": "编辑",
  "comments.delete": "删除",
  "comments.delete_confirm": "删除评论 “{body}”? ",
  "comments.delete_success": "评论 “{body}” 已删除.",
  "comments.please_log_in": "登录才可以进行评论哦",
  "comments.parentCommentId": "上层评论ID",
  "comments.topLevelCommentId": "顶层评论ID",
  "comments.body": "内容",
  "comments.rate_limit_error": "请 {details} 秒后再次评论",

  "users.profile": "个人",
  "users.complete_profile": "请完善您的个人信息",
  "users.edit_account": "编辑账户",
  "users.edit_success": "用户 “{name}” 编辑成功",
  "users.log_in": "登陆",
  "users.log_out": "退出",
  "users.telescope.bio": "个人简介",
  "users.telescope.displayName": "用户名",
  "users.telescope.email": "邮箱",
  "users.telescope.twitterUsername": "Twitter名称",
  "users.telescope.website": "个人主页",
  "users.telescope.groups": "群组",
  "users.telescope.avatar": "头像",
  "users.notifications": "通知",
  "users.telescope.notifications_users": "新用户通知",
  "users.telescope.notifications_posts": "新帖子通知",
  "users.telescope.newsletter_subscribeToNewsletter": "订阅最新消息",
  "users.admin": "管理员",
  "users.isAdmin": "管理员",
  "users.posts": "帖子",
  "users.please_log_in": "请登陆",
  "users.cannot_post": "抱歉, 您没有权限在这个时间发布帖子",
  "users.subscribe": "订阅该用户发布的帖子",
  "users.unsubscribe": "取消订阅该用户发布的帖子",
  "users.subscribed": "您已订阅了 “{name}” 的帖子.",
  "users.unsubscribed": "你已取消订阅了 “{name}” 的帖子.",
  "users.subscribers": "订阅者",

  "categories": "类别",
  "categories.all": "所有类别",
  "categories.edit": "编辑类别",
  "categories.new": "新类别",
  "categories.delete": "删除类别",
  "categories.name": "名称",
  "categories.description": "描述",
  "categories.order": "排序",
  "categories.slug": "Slug",
  "categories.image": "图片",
  "categories.parentId": "父类ID",
  "categories.subscribe": "订阅该类别的帖子",
  "categories.unsubscribe": "取消订阅该类别的帖子",
  "categories.subscribed": "你已经订阅了 “{name}” 的帖子.",
  "categories.unsubscribed": "你已经取消订阅了 “{name}” 的帖子.",
  "categories.subscribed_categories" : "已经订阅的类别",

  "settings": "设置",
  "settings.json_message": "Note: settings already provided in your <code>settings.json</code> file will be disabled.",
  "settings.edit": "修改设置",
  "settings.edited": "设置已修改成功 (请重新加载).",
  "settings.title": "标题",
  "settings.siteUrl": "网址链接",
  "settings.tagline": "标语",
  "settings.description": "描述",
  "settings.siteImage": "网站图片",
  "settings.defaultEmail": "默认邮箱",
  "settings.mailUrl": "邮箱地址",
  "settings.scoreUpdate": "评分更新",
  "settings.postInterval": "发布间隔",
  "settings.RSSLinksPointTo": "RSS Links Point To",
  "settings.commentInterval": "评论间隔",
  "settings.maxPostsPerDay": "每日最多发帖数",
  "settings.startInvitesCount": "Start Invites Count",
  "settings.postsPerPage": "每页帖子数量",
  "settings.logoUrl": "Logo 网址链接",
  "settings.logoHeight": "Logo 高度",
  "settings.logoWidth": "Logo 宽度",
  "settings.faviconUrl": "Favicon 网址链接",
  "settings.twitterAccount": "Twitter 账户",
  "settings.facebookPage": "Facebook 主页",
  "settings.googleAnalyticsId": "Google Analytics ID",
  "settings.locale": "语言环境",
  "settings.requireViewInvite": "Require View Invite",
  "settings.requirePostInvite": "Require Post Invite",
  "settings.requirePostsApproval": "Require Posts Approval",
  "settings.scoreUpdateInterval": "评分更新间隔",

  "app.loading": "加载中…",
  "app.404": "抱歉, 未找到页面.",
  "app.powered_by": "Powered by Telescope",
  "app.or": "Or",
  "app.noPermission": "抱歉, 您没有权限.",

  "newsletter": "最新消息",
  "newsletter.subscribe": "订阅",
  "newsletter.unsubscribe": "取消订阅",
  "newsletter.subscribe_prompt": "订阅我们的最新消息",
  "newsletter.email": "您的邮箱",
  "newsletter.success_message": "感谢订阅!",

  "admin": "管理员",
  "notifications": "通知",
};
